moves:
    flatter:
        description: "Express admiration or praise for the other agent's qualities, achievements, or ideas"
        effect: "Builds rapport and trust, may make the other agent more receptive"
        example: "Your experience in [field] is truly impressive, and your insights about [topic] are fascinating."

    challenge:
        description: "Question or probe the other agent's assumptions, beliefs, or statements"
        effect: "Stimulates deeper discussion and critical thinking"
        example: "That's an interesting perspective, but have you considered [alternative viewpoint]?"

    defend:
        description: "Protect and justify one's position, beliefs, or statements when challenged"
        effect: "Maintains credibility and conviction in one's stance"
        example: "I stand by my view because [reasoning], and my experience has shown that [evidence]."

    defuse:
        description: "Reduce tension or conflict by finding common ground or redirecting the conversation"
        effect: "Prevents escalation and maintains productive dialogue"
        example: "I see where you're coming from, and perhaps we can find middle ground on [aspect]."

    attack:
        description: "Directly criticize or oppose the other agent's position, beliefs, or statements"
        effect: "Creates conflict and forces the other agent to defend or reconsider"
        example: "Your argument is flawed because [reason], and here's why that matters..."

    entrust:
        description: "Share personal or vulnerable information to build trust and deepen connection"
        effect: "Creates intimacy and encourages reciprocal sharing"
        example: "Let me share a personal experience about [topic] that shaped my perspective..."
